[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dmpe"
version = "0.3.1"
authors = [
  { name="Hendrik Vater", email="vater@lea.uni-paderborn.de" },
]
description = "Excitation of exciting systems through differentiable model predictive excitation"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]
dependencies = [
    "jax",
    "equinox",
    "diffrax",
    "numpy>=2.5.3",
    "scipy>=1.18.1",
    "tqdm>=4.70.0",
    "optax>=0.2.8",
    "dm-haiku>=0.0.17",
    "pymoo>=0.6.2",
    "exciting-environments>=0.3.1",
]

[project.optional-dependencies]
cuda12 = ["exciting_environments[cuda12]"]
cuda13 = ["exciting_environments[cuda13]"]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=5.0.0",
]

[tool.uv.sources]
exciting_environments = { workspace = true }

[project.urls]
Homepage = "https://github.com/ExcitingSystems/DMPE"
Issues = "https://github.com/ExcitingSystems/DMPE/issues"

[tool.hatch.build.targets.wheel]
packages = ["dmpe"]


[tool.pytest.ini_options]
pythonpath = [
    "."
]